version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8000:8000"  # 호스트 8000 포트를 컨테이너 8000 포트에 매핑
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Nginx 설정 파일 매핑
      - /etc/letsencrypt:/etc/letsencrypt  # SSL 인증서 경로 매핑
    depends_on:
      - django_app

  django_app:
    build:
      context: ./app
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app  # Django 프로젝트 매핑
    expose:
      - "8000"  # 내부에서 Nginx가 접근 가능한 포트

